[settings]
  ID = "hippo-docs"

[build]
  base = "/"
  publish = "public"
  # Set BASE_URL to the production URL, or use $URL for the netlify staging site
  command = "BASE_URL=$URL make deploy"

[build.environment]
  HUGO_VERSION = "0.89.4"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "BASE_URL=$PRIME_DEPLOY_URL make deploy"

[context.branch-deploy]
  command = "BASE_URL=$PRIME_DEPLOY_URL make deploy"
